FROM node:22-bookworm-slim

WORKDIR /app

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
    nano \
    iputils-ping \
    net-tools \
    tree \
    curl \
    locales \
    tzdata \
    && localedef -i ja_JP -f UTF-8 ja_JP.UTF-8

RUN npm install -g pnpm@11.2.2

ENV LANG=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

CMD ["sleep", "infinity"]
